image: ubuntu:20.04

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y cmake git make g++
  script:
    - cmake -S . -B build
    - cmake --build build

test:
  stage: test
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y cmake git make g++ gcovr
  script:
    - cmake -S . -B build -D ENABLE_COVERAGE=ON
    - cmake --build build
    - (cd build && ctest)
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --exclude build/_deps/
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      cobertura: coverage.xml
